apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject.yaml
  - app-cilium.yaml
  - app-operators.yaml
  - app-platform.yaml
  - app-harbor.yaml
  - app-data-services.yaml
  - app-conduct.yaml
  - app-identity.yaml
  - app-zitadel.yaml
  - app-agent-sandbox-controller.yaml
  - app-sbx-gateway.yaml
  - app-sbx-templates.yaml
  - app-rabbitmq.yaml
  - app-qdrant.yaml
  - app-litellm.yaml
  - external-secret-argocd-uniquecr.yaml
  - app-chat.yaml
  - app-web-app-chat.yaml
  - app-web-app-admin.yaml
  - app-web-app-knowledge-upload.yaml
  - app-backend-chat.yaml
  - app-app-repository.yaml
  - app-assistants-core.yaml
  - app-scope-management.yaml
  - app-configuration.yaml
  - app-event-socket.yaml
  - app-ingestion.yaml
