apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    # pods need privileged; keep PSa from warning
    pod-security.kubernetes.io/enforce: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
