apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - routes-backend.yaml
  - external-secret-redis.yaml
  - obc-chat-storage.yaml
  - ../../../components/chat
  - external-secret-db.yaml
  - external-secret-rabbitmq.yaml
  - external-secret-app-secrets.yaml
  - route-chat.yaml
  - route-admin.yaml
  - route-knowledge-upload.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hello-openshift
      unique.ag/environment: sbx
