apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    unique.ag/layer: conduct
---
apiVersion: v1
kind: Namespace
metadata:
  name: sbx
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    unique.ag/layer: conduct
