apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hello-openshift-system.yaml
  - hello-openshift-data.yaml
  - hello-openshift-monitoring.yaml
  - external-secrets.yaml
