apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/identity/zitadel
  - external-secret-zitadel.yaml
  - route-zitadel.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hello-openshift
      unique.ag/environment: sbx
